### Q.3. Use the dataset Data1.csv to implement the list of classification models below in order to predict whether a tumor is malign or beginning. The dependent variable in this dataset is Class, it is equal to 2 if the tumor is benign and 4 if it is malign. The remaining columns are features that describe different characteristics of each tumor.

In [144]:
from sklearn import svm
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics
import seaborn as sb

In [145]:
dataset = pd.read_csv('Data1.csv')

In [146]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [147]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

### 1. Logistic Regression

In [148]:
from sklearn.linear_model import LogisticRegression

In [149]:
logisticRegr = LogisticRegression()

Training the model on the data, storing the information learned from the data
Model is learning the relationship between digits (x_train) and labels (y_train).

In [150]:
logisticRegr.fit(x_train, y_train)

LogisticRegression()

Predict labels for new data. Uses the information the model learned during the model training process.

In [151]:
logisticRegr.predict(x_test[0].reshape(1,-1))

array([2], dtype=int64)

Predict for Multiple Observations at Once

In [152]:
logisticRegr.predict(x_test[0:10])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

Make predictions on entire test data.

In [153]:
predictions = logisticRegr.predict(x_test)

Let's see the accuracy of the model using the score method:

In [154]:
score = logisticRegr.score(x_test, y_test)
print("Accuracy: {:.2f} %".format(score*100))

Accuracy: 63.50 %


In [155]:
cm = metrics.confusion_matrix(y_test, predictions)
print(cm)

[[87  0]
 [50  0]]


### 2. Decision Tree Classifier

#### 2.1. Let's create a Decision Tree Model using Scikit-learn. Import Decision Tree Classifier

In [156]:
from sklearn.tree import DecisionTreeClassifier

#### 2.2. Create Decision Tree classifer object.

In [157]:
clf1 = DecisionTreeClassifier()

#### 2.3. Train Decision Tree Classifer.

In [158]:
clf1 = clf1.fit(x_train, y_train)

#### 2.4. Predict the response for test dataset.

In [159]:
y_pred = clf1.predict(x_test)

Let's estimate, how accurately the classifier or model can predict whether a tumor is malign or bening. Accuracy can be computed by comparing actual test set values and predicted values.



In [160]:
print("Accuracy: {:.2f} %".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy: 93.43 %


### 3. Random Forest Classifier (with nb_trees = 10)

#### 3.1. Import Random Forest Model.

In [161]:
from sklearn.ensemble import RandomForestClassifier

#### 3.2. Create a Gaussian Classifier.

In [162]:
clf=RandomForestClassifier(n_estimators=10)


#### 3.3. Train the model using the training sets y_pred=clf.predict(X_test)


In [163]:
clf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=10)

In [164]:
y_pred=clf.predict(x_test)

#### 3.4. After training, check the accuracy using actual and predicted values.

In [165]:
print("Accuracy: {:.2f} %".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy: 96.35 %


### 4. K- Nearest Neighbors (K-NN)

In [166]:
from sklearn.neighbors import KNeighborsClassifier

In [167]:
neigh = KNeighborsClassifier(n_neighbors=3)

In [168]:
neigh.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [169]:
y_pred = neigh.predict(x_test)

#### 4.4. After training, check the accuracy using actual and predicted values.

In [170]:
print("Accuracy: {:.2f} %".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy: 62.77 %


### 5. Naive Bayes

In [171]:
# training the model on training set
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [172]:
# making predictions on the testing set
y_pred = gnb.predict(x_test)

In [173]:
# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy: {:.2f}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Gaussian Naive Bayes model accuracy: 83.21%


### 6. Support Vector Machine (SVM)

In [174]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

#### 6.2. Train the SVC classifier

In [175]:
clf = svm.SVC()
clf.fit(x_train, y_train)

SVC()

#### 6.3 Make predictions and compare the results by displaying the predicted values of y next to the test values of y in a two-dimensional array.

In [176]:
y_pred = clf.predict(X_test)
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2], dtype=int64)

#### 6.4. Create and print the Confusion Matrix and the accuracy score of the model and interpret the two.

In [177]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("SVC model accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred)*100))

[[87  0]
 [50  0]]
SVC model accuracy: 63.50%


## Random forest classifier is the best model!